project:
  type: website
  output-dir: docs

website:
  title: "Cooper Maughan - Data Science Portfolio"
  description: "A showcase of my data science projects and learning journey"

  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "About Me"
        href: about.md
      - text: "Projects"
        menu:
          - text: "Tutorial"
            href: tutorial_1.qmd
          - text: "All Projects"
            href: projects/index.md
          - text: "---"
          - text: "Exploratory Data Analysis"
            href: projects/eda.qmd
          # - text: "Data Acquisition"
          #   href: projects/data-acquisition.qmd
          # - text: "Final Project"
          #   href: projects/final-project.qmd
    right:
      - icon: github
        href: https://github.com/mcooperjay
      - icon: linkedin
        href: https://www.linkedin.com/in/cooper-maughan-95660a301/

  sidebar:
    - title: "Projects"
      contents:
        - projects/index.md
        # - projects/eda.qmd
        # - projects/data-acquisition.qmd
        # - projects/final-project.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
    