project:
  type: website
  output-dir: docs

website:
  title: "Cooper Maughan - Data Science Portfolio"
  description: "A showcase of my data science projects and learning journey"

  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.html
      - text: "About Me"
        href: about.md
      - text: "Resume"
        href: resume.qmd
      - text: "Ministry of Sports"
        href: ministry_of_sports/index.md
      - text: "School Projects"
        menu:
          - text: "Tutorial"
            href: tutorial_1.qmd
          - text: "---"
          # - text: "Exploratory Data Analysis"
          #   href: projects/eda.qmd
          - text: "Data Acquisition"
            href: data-acquisition.md
          # - text: "Final Project"
          #   href: projects/final-project.qmd
    right:
      - icon: github
        href: https://github.com/mcooperjay
      - icon: linkedin
        href: https://www.linkedin.com/in/cooper-maughan-95660a301/
      - icon: whatsapp
        href: https://wa.me/mcooperjay

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    code-fold: true
    code-tools: false
    css: styles.css
    